// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: wheelie_packets.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tag: 0
type FireAndForgetPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // GUID
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`      // Type of Message (Application-level data container) stored in binary format in Payload field
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Application-level Message in binary format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FireAndForgetPacket) Reset() {
	*x = FireAndForgetPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FireAndForgetPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireAndForgetPacket) ProtoMessage() {}

func (x *FireAndForgetPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireAndForgetPacket.ProtoReflect.Descriptor instead.
func (*FireAndForgetPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{0}
}

func (x *FireAndForgetPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FireAndForgetPacket) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *FireAndForgetPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Tag: 1
type ConnectPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Client's GUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPacket) Reset() {
	*x = ConnectPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPacket) ProtoMessage() {}

func (x *ConnectPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPacket.ProtoReflect.Descriptor instead.
func (*ConnectPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectPacket) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Tag: 2
type ConnectResponsePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`        // Server's GUID
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // Response status code (0 - success, etc.)
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                  // Optional description of response status code, depends on concrete implementation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponsePacket) Reset() {
	*x = ConnectResponsePacket{}
	mi := &file_wheelie_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponsePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponsePacket) ProtoMessage() {}

func (x *ConnectResponsePacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponsePacket.ProtoReflect.Descriptor instead.
func (*ConnectResponsePacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectResponsePacket) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ConnectResponsePacket) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ConnectResponsePacket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Tag: 3
type SetupPacket struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // Client's protocol version
	Payload         []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                                        // Some client's setup information, reserverd for future extending, empty for current protocol version
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetupPacket) Reset() {
	*x = SetupPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupPacket) ProtoMessage() {}

func (x *SetupPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupPacket.ProtoReflect.Descriptor instead.
func (*SetupPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{3}
}

func (x *SetupPacket) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *SetupPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Tag: 4
type SetupResponsePacket struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // Server's protocol version
	CanResume       bool                   `protobuf:"varint,2,opt,name=can_resume,json=canResume,proto3" json:"can_resume,omitempty"`                  // If true, server is satisfied by client's protocol version and can continue communication. If false - server will disconnect after sending this packet
	Payload         []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                        // SetupResponsePacketPayload in binary form due to always correct SetupResponsePacket parsing. Can contain different fields depending on protocol version
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetupResponsePacket) Reset() {
	*x = SetupResponsePacket{}
	mi := &file_wheelie_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupResponsePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupResponsePacket) ProtoMessage() {}

func (x *SetupResponsePacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupResponsePacket.ProtoReflect.Descriptor instead.
func (*SetupResponsePacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{4}
}

func (x *SetupResponsePacket) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *SetupResponsePacket) GetCanResume() bool {
	if x != nil {
		return x.CanResume
	}
	return false
}

func (x *SetupResponsePacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SetupResponsePacketPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeedAuth      bool                   `protobuf:"varint,1,opt,name=need_auth,json=needAuth,proto3" json:"need_auth,omitempty"` // If true, client need to Auth first before resuming communication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupResponsePacketPayload) Reset() {
	*x = SetupResponsePacketPayload{}
	mi := &file_wheelie_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupResponsePacketPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupResponsePacketPayload) ProtoMessage() {}

func (x *SetupResponsePacketPayload) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupResponsePacketPayload.ProtoReflect.Descriptor instead.
func (*SetupResponsePacketPayload) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{5}
}

func (x *SetupResponsePacketPayload) GetNeedAuth() bool {
	if x != nil {
		return x.NeedAuth
	}
	return false
}

// Tag: 5
type AuthPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // Application-level Message with auth data. Transfered "as-is"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthPacket) Reset() {
	*x = AuthPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthPacket) ProtoMessage() {}

func (x *AuthPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthPacket.ProtoReflect.Descriptor instead.
func (*AuthPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{6}
}

func (x *AuthPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Tag: 6
type AuthResponsePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // Response status code (0 - success, etc.)
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                  // Optional description of response status code, depends on concrete implementation
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                          // Application-level Message with auth response data. Transfered "as-is"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponsePacket) Reset() {
	*x = AuthResponsePacket{}
	mi := &file_wheelie_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponsePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponsePacket) ProtoMessage() {}

func (x *AuthResponsePacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponsePacket.ProtoReflect.Descriptor instead.
func (*AuthResponsePacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{7}
}

func (x *AuthResponsePacket) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AuthResponsePacket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AuthResponsePacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Tag: 7
type PingPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // GUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingPacket) Reset() {
	*x = PingPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPacket) ProtoMessage() {}

func (x *PingPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPacket.ProtoReflect.Descriptor instead.
func (*PingPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{8}
}

func (x *PingPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Tag: 8
type PingResponsePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // GUID of PingPacket which is responded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponsePacket) Reset() {
	*x = PingResponsePacket{}
	mi := &file_wheelie_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponsePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponsePacket) ProtoMessage() {}

func (x *PingResponsePacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponsePacket.ProtoReflect.Descriptor instead.
func (*PingResponsePacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{9}
}

func (x *PingResponsePacket) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Tag: 9
type ClosePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // Status code with client's reason of closing connection (0 - application shutdown, etc.)
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                  // Optional description of status code, depends on concrete implementation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosePacket) Reset() {
	*x = ClosePacket{}
	mi := &file_wheelie_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePacket) ProtoMessage() {}

func (x *ClosePacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePacket.ProtoReflect.Descriptor instead.
func (*ClosePacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{10}
}

func (x *ClosePacket) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ClosePacket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Tag: 10
type DisconnectPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // Status code with server's reason of closing connection (0 - server shutdown, etc.)
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                  // Optional description of status code, depends on concrete implementation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectPacket) Reset() {
	*x = DisconnectPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectPacket) ProtoMessage() {}

func (x *DisconnectPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectPacket.ProtoReflect.Descriptor instead.
func (*DisconnectPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{11}
}

func (x *DisconnectPacket) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DisconnectPacket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Tag: 11
type GetPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // GUID
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`      // Type of Message (Application-level data container) stored in binary format in Payload field
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Application-level Message in binary format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPacket) Reset() {
	*x = GetPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPacket) ProtoMessage() {}

func (x *GetPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPacket.ProtoReflect.Descriptor instead.
func (*GetPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{12}
}

func (x *GetPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPacket) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Tag: 12
type GetResponsePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`     // GUID of GetPacket which is responded
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // Response status code (0 - success, etc.)
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                  // Optional description of response status code, depends on concrete implementation
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`                               // Type of Message (Application-level data container) stored in binary format in Payload field
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                          // Application-level Message in binary format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponsePacket) Reset() {
	*x = GetResponsePacket{}
	mi := &file_wheelie_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponsePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponsePacket) ProtoMessage() {}

func (x *GetResponsePacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponsePacket.ProtoReflect.Descriptor instead.
func (*GetResponsePacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{13}
}

func (x *GetResponsePacket) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetResponsePacket) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetResponsePacket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetResponsePacket) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetResponsePacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Tag: 13
type CriticalGetPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // GUID
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`      // Type of Message (Application-level data container) stored in binary format in Payload field
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Application-level Message in binary format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriticalGetPacket) Reset() {
	*x = CriticalGetPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriticalGetPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriticalGetPacket) ProtoMessage() {}

func (x *CriticalGetPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriticalGetPacket.ProtoReflect.Descriptor instead.
func (*CriticalGetPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{14}
}

func (x *CriticalGetPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CriticalGetPacket) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CriticalGetPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Tag: 14
type CriticalGetResponsePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`     // GUID of GetPacket which is responded
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // Response status code (0 - success, etc.)
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                  // Optional description of response status code, depends on concrete implementation
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`                               // Type of Message (Application-level data container) stored in binary format in Payload field
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                          // Application-level Message in binary format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriticalGetResponsePacket) Reset() {
	*x = CriticalGetResponsePacket{}
	mi := &file_wheelie_packets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriticalGetResponsePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriticalGetResponsePacket) ProtoMessage() {}

func (x *CriticalGetResponsePacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriticalGetResponsePacket.ProtoReflect.Descriptor instead.
func (*CriticalGetResponsePacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{15}
}

func (x *CriticalGetResponsePacket) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CriticalGetResponsePacket) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CriticalGetResponsePacket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CriticalGetResponsePacket) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CriticalGetResponsePacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Tag: 15
type ServerPushPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // GUID
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`      // Type of Message (Application-level data container) stored in binary format in Payload field
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Application-level Message in binary format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPushPacket) Reset() {
	*x = ServerPushPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPushPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPushPacket) ProtoMessage() {}

func (x *ServerPushPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPushPacket.ProtoReflect.Descriptor instead.
func (*ServerPushPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{16}
}

func (x *ServerPushPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerPushPacket) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ServerPushPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Tag: 16
type ServerPushAckPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // GUID of ServerPushPacket which receiving we want to acknowledge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPushAckPacket) Reset() {
	*x = ServerPushAckPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPushAckPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPushAckPacket) ProtoMessage() {}

func (x *ServerPushAckPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPushAckPacket.ProtoReflect.Descriptor instead.
func (*ServerPushAckPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{17}
}

func (x *ServerPushAckPacket) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Tag: 17
type CriticalServerPushPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // GUID
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`      // Type of Message (Application-level data container) stored in binary format in Payload field
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Application-level Message in binary format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriticalServerPushPacket) Reset() {
	*x = CriticalServerPushPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriticalServerPushPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriticalServerPushPacket) ProtoMessage() {}

func (x *CriticalServerPushPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriticalServerPushPacket.ProtoReflect.Descriptor instead.
func (*CriticalServerPushPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{18}
}

func (x *CriticalServerPushPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CriticalServerPushPacket) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CriticalServerPushPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Tag: 18
type CriticalServerPushAckPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // GUID of ServerPushPacket which receiving we want to acknowledge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriticalServerPushAckPacket) Reset() {
	*x = CriticalServerPushAckPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriticalServerPushAckPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriticalServerPushAckPacket) ProtoMessage() {}

func (x *CriticalServerPushAckPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriticalServerPushAckPacket.ProtoReflect.Descriptor instead.
func (*CriticalServerPushAckPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{19}
}

func (x *CriticalServerPushAckPacket) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Tag: 19
type MultiPartPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`  // GUID of proceeding MultiGetPacket or MultiPushPacket
	PartIndex     int32                  `protobuf:"varint,2,opt,name=part_index,json=partIndex,proto3" json:"part_index,omitempty"` // Index of transfered part of resource
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                       // Part of fractured Message in binary format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiPartPacket) Reset() {
	*x = MultiPartPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPartPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPartPacket) ProtoMessage() {}

func (x *MultiPartPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPartPacket.ProtoReflect.Descriptor instead.
func (*MultiPartPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{20}
}

func (x *MultiPartPacket) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MultiPartPacket) GetPartIndex() int32 {
	if x != nil {
		return x.PartIndex
	}
	return 0
}

func (x *MultiPartPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Tag: 20
type MultiPartAckPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`  // GUID of proceeding MultiGetPacket or MultiPushPacket
	PartIndex     int32                  `protobuf:"varint,2,opt,name=part_index,json=partIndex,proto3" json:"part_index,omitempty"` // Index of acknowledged part of resource
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiPartAckPacket) Reset() {
	*x = MultiPartAckPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPartAckPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPartAckPacket) ProtoMessage() {}

func (x *MultiPartAckPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPartAckPacket.ProtoReflect.Descriptor instead.
func (*MultiPartAckPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{21}
}

func (x *MultiPartAckPacket) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MultiPartAckPacket) GetPartIndex() int32 {
	if x != nil {
		return x.PartIndex
	}
	return 0
}

// Tag: 21
type MultiGetPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // GUID
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                            // Type of Message (Application-level data container) stored in binary format in Payload field
	StartPart     int32                  `protobuf:"varint,3,opt,name=start_part,json=startPart,proto3" json:"start_part,omitempty"` // The part of multipart resource to start downloading from. Indexing starts with 0
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                       // Application-level Message in binary format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiGetPacket) Reset() {
	*x = MultiGetPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiGetPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiGetPacket) ProtoMessage() {}

func (x *MultiGetPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiGetPacket.ProtoReflect.Descriptor instead.
func (*MultiGetPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{22}
}

func (x *MultiGetPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MultiGetPacket) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MultiGetPacket) GetStartPart() int32 {
	if x != nil {
		return x.StartPart
	}
	return 0
}

func (x *MultiGetPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Tag: 22
type MultiGetResponsePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`           // GUID of MultiGetPacket which is responded
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`       // Response status code (0 - success, etc.)
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                        // Optional description of response status code, depends on concrete implementation
	MaxPartSize   int32                  `protobuf:"varint,4,opt,name=max_part_size,json=maxPartSize,proto3" json:"max_part_size,omitempty"`  // Maximum size of each resource's part in bytes
	ResourceSize  int64                  `protobuf:"varint,5,opt,name=resource_size,json=resourceSize,proto3" json:"resource_size,omitempty"` // Resource's size in bytes
	Type          int32                  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`                                     // Type of fractured Message, depends on Application-level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiGetResponsePacket) Reset() {
	*x = MultiGetResponsePacket{}
	mi := &file_wheelie_packets_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiGetResponsePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiGetResponsePacket) ProtoMessage() {}

func (x *MultiGetResponsePacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiGetResponsePacket.ProtoReflect.Descriptor instead.
func (*MultiGetResponsePacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{23}
}

func (x *MultiGetResponsePacket) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MultiGetResponsePacket) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *MultiGetResponsePacket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MultiGetResponsePacket) GetMaxPartSize() int32 {
	if x != nil {
		return x.MaxPartSize
	}
	return 0
}

func (x *MultiGetResponsePacket) GetResourceSize() int64 {
	if x != nil {
		return x.ResourceSize
	}
	return 0
}

func (x *MultiGetResponsePacket) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// Tag: 23
type MultiPushPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                          // GUID
	MaxPartSize   int32                  `protobuf:"varint,2,opt,name=max_part_size,json=maxPartSize,proto3" json:"max_part_size,omitempty"`  // Maximum size of each resource's part in bytes
	ResourceSize  int64                  `protobuf:"varint,3,opt,name=resource_size,json=resourceSize,proto3" json:"resource_size,omitempty"` // Resource's size in bytes
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`                                     // Type of Message (Application-level data container) stored in binary format in Payload field
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                                // Application-level Message in binary format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiPushPacket) Reset() {
	*x = MultiPushPacket{}
	mi := &file_wheelie_packets_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPushPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPushPacket) ProtoMessage() {}

func (x *MultiPushPacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPushPacket.ProtoReflect.Descriptor instead.
func (*MultiPushPacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{24}
}

func (x *MultiPushPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MultiPushPacket) GetMaxPartSize() int32 {
	if x != nil {
		return x.MaxPartSize
	}
	return 0
}

func (x *MultiPushPacket) GetResourceSize() int64 {
	if x != nil {
		return x.ResourceSize
	}
	return 0
}

func (x *MultiPushPacket) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MultiPushPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Tag: 24
type MultiPushResponsePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`     // GUID of MultiPushPacket which is responded
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // Response status code (0 - success, etc.)
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                  // Optional description of response status code, depends on concrete implementation
	StartPart     int32                  `protobuf:"varint,4,opt,name=start_part,json=startPart,proto3" json:"start_part,omitempty"`    // The part of multipart resource to start uploading from. Indexing starts with 0
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`                               // Type of fractured Message, depends on Application-level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiPushResponsePacket) Reset() {
	*x = MultiPushResponsePacket{}
	mi := &file_wheelie_packets_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiPushResponsePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiPushResponsePacket) ProtoMessage() {}

func (x *MultiPushResponsePacket) ProtoReflect() protoreflect.Message {
	mi := &file_wheelie_packets_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiPushResponsePacket.ProtoReflect.Descriptor instead.
func (*MultiPushResponsePacket) Descriptor() ([]byte, []int) {
	return file_wheelie_packets_proto_rawDescGZIP(), []int{25}
}

func (x *MultiPushResponsePacket) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MultiPushResponsePacket) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *MultiPushResponsePacket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MultiPushResponsePacket) GetStartPart() int32 {
	if x != nil {
		return x.StartPart
	}
	return 0
}

func (x *MultiPushResponsePacket) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

var File_wheelie_packets_proto protoreflect.FileDescriptor

const file_wheelie_packets_proto_rawDesc = "" +
	"\n" +
	"\x15wheelie_packets.proto\"S\n" +
	"\x13FireAndForgetPacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\",\n" +
	"\rConnectPacket\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"w\n" +
	"\x15ConnectResponsePacket\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"R\n" +
	"\vSetupPacket\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"y\n" +
	"\x13SetupResponsePacket\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"can_resume\x18\x02 \x01(\bR\tcanResume\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"9\n" +
	"\x1aSetupResponsePacketPayload\x12\x1b\n" +
	"\tneed_auth\x18\x01 \x01(\bR\bneedAuth\"&\n" +
	"\n" +
	"AuthPacket\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"q\n" +
	"\x12AuthResponsePacket\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\x1c\n" +
	"\n" +
	"PingPacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x12PingResponsePacket\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"P\n" +
	"\vClosePacket\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"U\n" +
	"\x10DisconnectPacket\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"I\n" +
	"\tGetPacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xa3\x01\n" +
	"\x11GetResponsePacket\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"Q\n" +
	"\x11CriticalGetPacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xab\x01\n" +
	"\x19CriticalGetResponsePacket\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"P\n" +
	"\x10ServerPushPacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"4\n" +
	"\x13ServerPushAckPacket\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"X\n" +
	"\x18CriticalServerPushPacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"<\n" +
	"\x1bCriticalServerPushAckPacket\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"i\n" +
	"\x0fMultiPartPacket\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"part_index\x18\x02 \x01(\x05R\tpartIndex\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"R\n" +
	"\x12MultiPartAckPacket\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"part_index\x18\x02 \x01(\x05R\tpartIndex\"m\n" +
	"\x0eMultiGetPacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x1d\n" +
	"\n" +
	"start_part\x18\x03 \x01(\x05R\tstartPart\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\xd7\x01\n" +
	"\x16MultiGetResponsePacket\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\rmax_part_size\x18\x04 \x01(\x05R\vmaxPartSize\x12#\n" +
	"\rresource_size\x18\x05 \x01(\x03R\fresourceSize\x12\x12\n" +
	"\x04type\x18\x06 \x01(\x05R\x04type\"\x98\x01\n" +
	"\x0fMultiPushPacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\rmax_part_size\x18\x02 \x01(\x05R\vmaxPartSize\x12#\n" +
	"\rresource_size\x18\x03 \x01(\x03R\fresourceSize\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\xae\x01\n" +
	"\x17MultiPushResponsePacket\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_part\x18\x04 \x01(\x05R\tstartPart\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04typeB\x1fZ\x1dwheelie-client/internal/pb;pbb\x06proto3"

var (
	file_wheelie_packets_proto_rawDescOnce sync.Once
	file_wheelie_packets_proto_rawDescData []byte
)

func file_wheelie_packets_proto_rawDescGZIP() []byte {
	file_wheelie_packets_proto_rawDescOnce.Do(func() {
		file_wheelie_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wheelie_packets_proto_rawDesc), len(file_wheelie_packets_proto_rawDesc)))
	})
	return file_wheelie_packets_proto_rawDescData
}

var file_wheelie_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_wheelie_packets_proto_goTypes = []any{
	(*FireAndForgetPacket)(nil),         // 0: FireAndForgetPacket
	(*ConnectPacket)(nil),               // 1: ConnectPacket
	(*ConnectResponsePacket)(nil),       // 2: ConnectResponsePacket
	(*SetupPacket)(nil),                 // 3: SetupPacket
	(*SetupResponsePacket)(nil),         // 4: SetupResponsePacket
	(*SetupResponsePacketPayload)(nil),  // 5: SetupResponsePacketPayload
	(*AuthPacket)(nil),                  // 6: AuthPacket
	(*AuthResponsePacket)(nil),          // 7: AuthResponsePacket
	(*PingPacket)(nil),                  // 8: PingPacket
	(*PingResponsePacket)(nil),          // 9: PingResponsePacket
	(*ClosePacket)(nil),                 // 10: ClosePacket
	(*DisconnectPacket)(nil),            // 11: DisconnectPacket
	(*GetPacket)(nil),                   // 12: GetPacket
	(*GetResponsePacket)(nil),           // 13: GetResponsePacket
	(*CriticalGetPacket)(nil),           // 14: CriticalGetPacket
	(*CriticalGetResponsePacket)(nil),   // 15: CriticalGetResponsePacket
	(*ServerPushPacket)(nil),            // 16: ServerPushPacket
	(*ServerPushAckPacket)(nil),         // 17: ServerPushAckPacket
	(*CriticalServerPushPacket)(nil),    // 18: CriticalServerPushPacket
	(*CriticalServerPushAckPacket)(nil), // 19: CriticalServerPushAckPacket
	(*MultiPartPacket)(nil),             // 20: MultiPartPacket
	(*MultiPartAckPacket)(nil),          // 21: MultiPartAckPacket
	(*MultiGetPacket)(nil),              // 22: MultiGetPacket
	(*MultiGetResponsePacket)(nil),      // 23: MultiGetResponsePacket
	(*MultiPushPacket)(nil),             // 24: MultiPushPacket
	(*MultiPushResponsePacket)(nil),     // 25: MultiPushResponsePacket
}
var file_wheelie_packets_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wheelie_packets_proto_init() }
func file_wheelie_packets_proto_init() {
	if File_wheelie_packets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wheelie_packets_proto_rawDesc), len(file_wheelie_packets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wheelie_packets_proto_goTypes,
		DependencyIndexes: file_wheelie_packets_proto_depIdxs,
		MessageInfos:      file_wheelie_packets_proto_msgTypes,
	}.Build()
	File_wheelie_packets_proto = out.File
	file_wheelie_packets_proto_goTypes = nil
	file_wheelie_packets_proto_depIdxs = nil
}
